# Development Stage
FROM node:22-alpine AS dev

WORKDIR /app

COPY backend/package.json backend/package-lock.json ./
RUN npm install

COPY backend/. ./

CMD ["npx", "nodemon", "server.js"]

# Production Stage
# Production Stage
FROM node:22-alpine AS prod

WORKDIR /app

COPY backend/package.json backend/package-lock.json ./
# Skips dev dependencies
RUN npm install --omit=dev

COPY --from=dev /app ./

CMD ["node", "server.js"]